export type TeletextLine = { text: string; color?: TeletextColor };
export type TeletextColor = "y" | "w" | "c" | "g" | "m" | "r";

export type TeletextPageDef = {
  num: number;
  title: string;
  lines: TeletextLine[];
};

/** Pàgines 100–899. Edita aquí el text d’Espai42 (màx. 40 caràcters per línia al cos). */
export const TELETEXT_PAGES: TeletextPageDef[] = [
  {
    num: 100,
    title: "ESPai42",
    lines: [
      { text: "  ESPai42                      ", color: "y" },
      { text: "  Coworking creatiu            ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Artesania, art i oficis      ", color: "w" },
      { text: "  amb espai per a tallers.     ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Index de pàgines:            ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  101  Qui som                 ", color: "y" },
      { text: "  102  Serveis                 ", color: "y" },
      { text: "  103  Agenda                  ", color: "y" },
      { text: "  104  Projectes residents     ", color: "y" },
      { text: "  105  Contacte                ", color: "y" },
      { text: "  106  Joc de la serp          ", color: "y" },
      { text: "  107  Xarxes socials          ", color: "y" },
      { text: "  300  Residents (subindex)    ", color: "y" },
      { text: "  Teclegeu el numero de pagina ", color: "c" },
      { text: "  al comandament del mobil.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 100       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 101,
    title: "QUI SOM",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  QUI SOM                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Espai42 és una associació    ", color: "w" },
      { text: "  sense ànim de lucre que      ", color: "w" },
      { text: "  acull oficis creatius i      ", color: "w" },
      { text: "  tallers d’artesania i art.   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Volem un espai obert on      ", color: "c" },
      { text: "  compartir eines, idees i     ", color: "c" },
      { text: "  projectes amb el barri.      ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornada a l’index: pàg 100   ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 101       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 102,
    title: "SERVEIS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  SERVEIS                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  * Espai de coworking         ", color: "w" },
      { text: "  * Aules i taules de treball  ", color: "w" },
      { text: "  * Tallers equipats           ", color: "w" },
      { text: "  * Embarcadors i magatzem     ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  * Activitats i formacions     ", color: "c" },
      { text: "  * Exposicions i mostres      ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Consulteu la pàg 105 per     ", color: "m" },
      { text: "  contacte i visites.          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 102       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 103,
    title: "AGENDA",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  AGENDA (exemple)             ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  DL  10:00  Cafè creatiu      ", color: "w" },
      { text: "  DC  18:00  Taller obert      ", color: "w" },
      { text: "  DV  19:00  Portes obertes    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Calendari a la web i a les  ", color: "c" },
      { text: "  xarxes (dates orientatives). ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Voleu proposar una activitat?", color: "m" },
      { text: "  Escriviu-nos (pàg 105).      ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 103       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 104,
    title: "PROJECTES",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  PROJECTES RESIDENTS          ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Nou format en arbre!         ", color: "w" },
      { text: "  Subindex principal: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  310 Art                      ", color: "c" },
      { text: "  320 Artesania                ", color: "c" },
      { text: "  330 Makers                   ", color: "c" },
      { text: "  340 Oficis                   ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Cada bloc te perfils i       ", color: "m" },
      { text: "  contacte d'exemple.          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 104       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 105,
    title: "CONTACTE",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  CONTACTE                     ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Correu: info@espai42.cat     ", color: "w" },
      { text: "  Web:    https://espai42.org  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Horari secretaria (exemple): ", color: "c" },
      { text: "  DM i DJ  17:00 - 20:00       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Hi ha QR per al teletext     ", color: "m" },
      { text: "  i QR per la web oficial.     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 105       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 106,
    title: "JOC SERP",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JOC DE LA SERP              ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Controla amb el comandament ", color: "w" },
      { text: "  i les fletxes de direccio.  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  El tauler es mostra a la    ", color: "c" },
      { text: "  dreta de la pantalla.       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Torna a index: pag 100      ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 106       ESPai42       ", color: "g" },
    ],
  },
  {
    num: 107,
    title: "XARXES",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  XARXES SOCIALS               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Instagram: @espai42          ", color: "w" },
      { text: "  Feed pixelat en preparacio   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Previstes miniatures         ", color: "c" },
      { text: "  de les darreres publicacions ", color: "c" },
      { text: "  en format retro teletext.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Mentrestant: visita la web   ", color: "m" },
      { text: "  i el perfil oficial.         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 107       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 300,
    title: "RESIDENTS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  PROJECTES RESIDENTS          ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  SUBINDEX 300                 ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  310  ART                     ", color: "c" },
      { text: "  320  ARTESANIA               ", color: "c" },
      { text: "  330  MAKERS                  ", color: "c" },
      { text: "  340  OFICIS                  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Usa el comandament per       ", color: "m" },
      { text: "  entrar a cada categoria.     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 300       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 310,
    title: "ART",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ART / INDEX                  ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart homenatge: EL CRIT  ", color: "m" },
      { text: "  Versio teletext de mostra.   ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  311  Ona Vilaro              ", color: "c" },
      { text: "  312  Biel Carranza           ", color: "c" },
      { text: "  313  Rita Solans             ", color: "c" },
      { text: "  314  Marc Elies              ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 310       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 311,
    title: "ARTISTA 311",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ONA VILARO                   ", color: "y" },
      { text: "  Artista visual resident      ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: explora memòria i       ", color: "c" },
      { text: "  paisatge amb collage i tinta.", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: ona@espai42.art    ", color: "m" },
      { text: "  IG: @ona.vilaro.studio       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 311       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 312,
    title: "ARTISTA 312",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  BIEL CARRANZA                ", color: "y" },
      { text: "  Il·lustrador resident        ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: personatges urbans      ", color: "c" },
      { text: "  en tinta digital i mural.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: biel@espai42.art   ", color: "m" },
      { text: "  Web: bielcarranza.studio     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 312       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 313,
    title: "ARTISTA 313",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  RITA SOLANS                  ", color: "y" },
      { text: "  Fotògrafa resident           ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: retrat analògic,        ", color: "c" },
      { text: "  llum natural i escena local. ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: rita@espai42.art   ", color: "m" },
      { text: "  IG: @rita.solans.photo       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 313       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 314,
    title: "ARTISTA 314",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  MARC ELIES                   ", color: "y" },
      { text: "  Pintor resident              ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: geometria, color i      ", color: "c" },
      { text: "  narrativa abstracta.         ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: marc@espai42.art   ", color: "m" },
      { text: "  Tel: +34 600 111 314         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 314       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 320,
    title: "ARTESANIA",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ARTESANIA / INDEX            ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart: artesa fent        ", color: "m" },
      { text: "  terrissa al torn ceràmic.    ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  321  Laia Pons (ceràmica)    ", color: "c" },
      { text: "  322  Jan Roca (fusta)        ", color: "c" },
      { text: "  323  Nur Alcaraz (teixit)    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 320       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 321,
    title: "ARTESA 321",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  LAIA PONS / CERAMICA         ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: peces utilitàries       ", color: "c" },
      { text: "  esmaltades i cocció lenta.   ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: laia@espai42.art   ", color: "m" },
      { text: "  IG: @laiapons.ceramica       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 321       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 322,
    title: "ARTESA 322",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JAN ROCA / FUSTA             ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: mobiliari petit i       ", color: "c" },
      { text: "  joguines de fusta recuperada.", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: jan@espai42.art    ", color: "m" },
      { text: "  Web: janroca.taller          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 322       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 323,
    title: "ARTESA 323",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  NUR ALCARAZ / TEXTIL         ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: tint natural, patrons   ", color: "c" },
      { text: "  i peces de producció curta.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: nur@espai42.art    ", color: "m" },
      { text: "  IG: @nuralcaraz.textil       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 323       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 330,
    title: "MAKERS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  MAKERS / INDEX               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart inspirat en         ", color: "m" },
      { text: "  Leonardo da Vinci.           ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  331  Ada Prat (electrònica)  ", color: "c" },
      { text: "  332  Pol Serra (impressió 3D)", color: "c" },
      { text: "  333  Iris Valls (robots)     ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 330       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 331,
    title: "MAKER 331",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ADA PRAT / ELECTRONICA       ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: sintetitzadors DIY i    ", color: "c" },
      { text: "  sensors per instal·lacions.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: ada@espai42.art    ", color: "m" },
      { text: "  IG: @adaprat.makes           ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 331       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 332,
    title: "MAKER 332",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  POL SERRA / IMPRESSIO 3D     ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: prototips, recanvis      ", color: "c" },
      { text: "  i eines per tallers locals.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: pol@espai42.art    ", color: "m" },
      { text: "  Web: polserra.maker          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 332       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 333,
    title: "MAKER 333",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  IRIS VALLS / ROBOTICA        ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: robots cinètics i       ", color: "c" },
      { text: "  automatismes escènics.       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: iris@espai42.art   ", color: "m" },
      { text: "  IG: @iris.valls.lab          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 333       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 340,
    title: "OFICIS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  OFICIS / INDEX               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart: persona bufant     ", color: "m" },
      { text: "  vidre al forn del taller.    ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  341  Joana Clot (vidre)      ", color: "c" },
      { text: "  342  Arnau Gelabert (ferro)  ", color: "c" },
      { text: "  343  Teia Roig (enquadern.)  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 340       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 341,
    title: "OFICI 341",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JOANA CLOT / VIDRE           ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: llumins, gerros i       ", color: "c" },
      { text: "  escultura de vidre bufat.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: joana@espai42.art  ", color: "m" },
      { text: "  IG: @joanaclot.glass         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 341       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 342,
    title: "OFICI 342",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ARNAU GELABERT / FERRO       ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: forja artística i       ", color: "c" },
      { text: "  estructures per interior.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: arnau@espai42.art  ", color: "m" },
      { text: "  Tel: +34 600 340 342         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 342       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 343,
    title: "OFICI 343",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  TEIA ROIG / ENQUADERNACIO    ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: llibreta artesanal,     ", color: "c" },
      { text: "  pell i paper reciclat.       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: teia@espai42.art   ", color: "m" },
      { text: "  Web: teiaroig.ofici          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 343       ESPai42        ", color: "g" },
    ],
  },
];

const pageMap = new Map(TELETEXT_PAGES.map((p) => [p.num, p]));

export function getTeletextPage(num: number): TeletextPageDef | undefined {
  return pageMap.get(num);
}

export const KNOWN_PAGE_NUMS = TELETEXT_PAGES.map((p) => p.num).sort((a, b) => a - b);
