export type TeletextLine = { text: string; color?: TeletextColor; bg?: TeletextColor };
export type TeletextColor = "y" | "w" | "c" | "g" | "m" | "r";

export type TeletextPageDef = {
  num: number;
  title: string;
  lines: TeletextLine[];
};

/** Pàgines 100–899. Edita aquí el text d’Espai42 (màx. 40 caràcters per línia al cos). */
export const TELETEXT_PAGES: TeletextPageDef[] = [
  {
    num: 100,
    title: "INFO ESPAI42",
    lines: [
      { text: " INFO ESPAI42      ESPAI42 LOGO", color: "w" },
      { text: "                               ", color: "w", bg: "y" },
      { text: " SECCIO VERMELLA               ", color: "w", bg: "r" },
      { text: " 101 Qui som   102 Que fem     ", color: "w", bg: "r" },
      { text: " 103 Serveis  104 Espai42      ", color: "w", bg: "r" },
      { text: "                               ", color: "w", bg: "g" },
      { text: " SECCIO VERDA                  ", color: "w", bg: "g" },
      { text: " 201 Agenda    202 Activitats  ", color: "w", bg: "g" },
      { text: " 203 Tallers   204 Convocat.   ", color: "w", bg: "g" },
      { text: "                               ", color: "r", bg: "y" },
      { text: " SECCIO GROGA                  ", color: "r", bg: "y" },
      { text: " 300 Residents 310 Art         ", color: "r", bg: "y" },
      { text: " 320 Artesania 330 Makers      ", color: "r", bg: "y" },
      { text: " 340 Oficis                    ", color: "r", bg: "y" },
      { text: " SECCIO BLAVA                  ", color: "c" },
      { text: " 401 Contacte 402 Xarxes       ", color: "c" },
      { text: " 403 Partners                  ", color: "c" },
      { text: " Pàg 100    ESPAI42 EN DIRECTE ", color: "g" },
    ],
  },
  {
    num: 101,
    title: "QUI SOM",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  QUI SOM                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Espai42 és una associació    ", color: "w" },
      { text: "  sense ànim de lucre que      ", color: "w" },
      { text: "  acull oficis creatius i      ", color: "w" },
      { text: "  tallers d’artesania i art.   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Volem un espai obert on      ", color: "c" },
      { text: "  compartir eines, idees i     ", color: "c" },
      { text: "  projectes amb el barri.      ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornada a l’index: pàg 100   ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 101       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 102,
    title: "QUE FEM",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  QUE FEM                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Impulsem creacio local:      ", color: "w" },
      { text: "  art, artesania i tecnologia. ", color: "w" },
      { text: "  Fem exposicions, xarxa       ", color: "w" },
      { text: "  i suport entre residents.    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Veure agenda ampliada:       ", color: "c" },
      { text: "  pàgines 201 a 204.           ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte i xarxes: secció     ", color: "m" },
      { text: "  blava del teletext.          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 102       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 103,
    title: "SERVEIS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  SERVEIS                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  * Coworking creatiu          ", color: "w" },
      { text: "  * Tallers equipats           ", color: "w" },
      { text: "  * Assessorament projectes    ", color: "w" },
      { text: "  * Produccio i prototipat     ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  * Activitats i formacions    ", color: "c" },
      { text: "  * Mostres i esdeveniments    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Per col·laborar: pàg 403     ", color: "m" },
      { text: "  Per contactar: pàg 401       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 103       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 104,
    title: "ESPAI42",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ESPAI42                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Associacio coworking         ", color: "w" },
      { text: "  creatiu per artesans         ", color: "w" },
      { text: "  i artistes de proximitat.    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Navega per colors: vermell   ", color: "c" },
      { text: "  espai · verd agenda · groc   ", color: "c" },
      { text: "  residents · blau contacte.   ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Joc de la serp: pàg 501      ", color: "m" },
      { text: "  al banner verd inferior.     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 104       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 201,
    title: "AGENDA",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  AGENDA GENERAL               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  DM  10:00  Portes obertes    ", color: "w" },
      { text: "  DC  18:30  Sessio coworking  ", color: "w" },
      { text: "  DV  19:00  Mostra resident   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Altres seccions agenda:      ", color: "c" },
      { text: "  202 Activitats               ", color: "c" },
      { text: "  203 Tallers                  ", color: "c" },
      { text: "  204 Convocatories            ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar al home: pàg 100      ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 201       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 202,
    title: "ACTIVITATS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ACTIVITATS                   ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Clubs creatius setmanals     ", color: "w" },
      { text: "  sessions critiques obertes   ", color: "w" },
      { text: "  i laboratoris col·laboratius ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Calendari complet: pàg 201   ", color: "c" },
      { text: "  Tallers: pàg 203             ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Convocatories: pàg 204       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 202       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 203,
    title: "TALLERS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  TALLERS                      ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Ceramica, vidre, textil      ", color: "w" },
      { text: "  maker basics i prototipat    ", color: "w" },
      { text: "  de projectes personals.      ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Places i dates a agenda:     ", color: "c" },
      { text: "  pàg 201 i activitats 202.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Convocatories: pàg 204       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 203       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 204,
    title: "CONVOCATORIES",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  CONVOCATORIES                ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Obertura places residents    ", color: "w" },
      { text: "  i ajuts a produccio local.   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Consulta requisits per       ", color: "c" },
      { text: "  categories a secció groga.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte directe: pàg 401    ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 204       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 401,
    title: "CONTACTE",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  CONTACTE                     ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Correu: info@espai42.cat     ", color: "w" },
      { text: "  Web: https://espai42.org     ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Horari secretaria:           ", color: "c" },
      { text: "  DM i DJ 17:00 - 20:00        ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  QR control + QR web oficial  ", color: "m" },
      { text: "  visibles en aquesta pàgina.  ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 401       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 402,
    title: "XARXES",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  XARXES SOCIALS               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Instagram: @espai42          ", color: "w" },
      { text: "  Feed pixelat en preparacio   ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Proper pas: ultimes imatges  ", color: "c" },
      { text: "  en miniatura estil teletext. ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Web i contacte: pàg 401      ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 402       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 403,
    title: "PARTNERS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  PARTNERS I COLLABORACIONS    ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Xarxa local de tallers,      ", color: "w" },
      { text: "  escoles i entitats culturals.", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Si vols col·laborar:         ", color: "c" },
      { text: "  partners@espai42.cat         ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar contacte: pàg 401     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 403       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 501,
    title: "JOC SERP",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JOC DE LA SERP               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Control: COMENCA + fletxes   ", color: "w" },
      { text: "  al comandament mobil.        ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  El tauler apareix a la       ", color: "c" },
      { text: "  dreta de la pantalla TV.     ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a inici: pàg 100      ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 501       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 300,
    title: "RESIDENTS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  PROJECTES RESIDENTS          ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Índex projectes residents    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  310  ART                     ", color: "c" },
      { text: "  320  ARTESANIA               ", color: "c" },
      { text: "  330  MAKERS                  ", color: "c" },
      { text: "  340  OFICIS                  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Usa el comandament per       ", color: "m" },
      { text: "  entrar a cada categoria.     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 300       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 310,
    title: "ART",
    lines: [
      { text: "  ART / INDEX                  ", color: "y" },
      { text: "  TITO ART EN DIRECTE          ", color: "r", bg: "w" },
      { text: "                              ", color: "w" },
      { text: "  HOMENATGE PIXEL: EL CRIT     ", color: "m" },
      { text: "  _.-\"\"-._     .-\"\"-.          ", color: "w" },
      { text: " /  .-.  \\   /  .-. \\         ", color: "w" },
      { text: "|  /   \\  | |  /   \\ |        ", color: "w" },
      { text: "| | 0 0 | | | | 0 0 | |        ", color: "c" },
      { text: "| |  ^  | | | |  ^  | |        ", color: "c" },
      { text: "| | --- | | | | --- | |        ", color: "y" },
      { text: "|  \\___/  | |  \\___/  |       ", color: "y" },
      { text: " \\       /   \\       /        ", color: "w" },
      { text: "  `-.__.-'     `-.__.-'         ", color: "w" },
      { text: "  311 ONA   312 BIEL           ", color: "c" },
      { text: "  313 RITA  314 MARC           ", color: "c" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "  Pàg 310   TITO ART / ESP42   ", color: "g" },
    ],
  },
  {
    num: 311,
    title: "ARTISTA 311",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ONA VILARO                   ", color: "y" },
      { text: "  Artista visual resident      ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: explora memòria i       ", color: "c" },
      { text: "  paisatge amb collage i tinta.", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: ona@espai42.art    ", color: "m" },
      { text: "  IG: @ona.vilaro.studio       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 311       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 312,
    title: "ARTISTA 312",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  BIEL CARRANZA                ", color: "y" },
      { text: "  Il·lustrador resident        ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: personatges urbans      ", color: "c" },
      { text: "  en tinta digital i mural.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: biel@espai42.art   ", color: "m" },
      { text: "  Web: bielcarranza.studio     ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 312       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 313,
    title: "ARTISTA 313",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  RITA SOLANS                  ", color: "y" },
      { text: "  Fotògrafa resident           ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: retrat analògic,        ", color: "c" },
      { text: "  llum natural i escena local. ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: rita@espai42.art   ", color: "m" },
      { text: "  IG: @rita.solans.photo       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 313       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 314,
    title: "ARTISTA 314",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  MARC ELIES                   ", color: "y" },
      { text: "  Pintor resident              ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Bio: geometria, color i      ", color: "c" },
      { text: "  narrativa abstracta.         ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: marc@espai42.art   ", color: "m" },
      { text: "  Tel: +34 600 111 314         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar index ART: pàg 310    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 314       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 320,
    title: "ARTESANIA",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ARTESANIA / INDEX            ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart: artesa fent        ", color: "m" },
      { text: "  terrissa al torn ceràmic.    ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  321  Laia Pons (ceràmica)    ", color: "c" },
      { text: "  322  Jan Roca (fusta)        ", color: "c" },
      { text: "  323  Nur Alcaraz (teixit)    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 320       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 321,
    title: "ARTESA 321",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  LAIA PONS / CERAMICA         ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: peces utilitàries       ", color: "c" },
      { text: "  esmaltades i cocció lenta.   ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: laia@espai42.art   ", color: "m" },
      { text: "  IG: @laiapons.ceramica       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 321       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 322,
    title: "ARTESA 322",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JAN ROCA / FUSTA             ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: mobiliari petit i       ", color: "c" },
      { text: "  joguines de fusta recuperada.", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: jan@espai42.art    ", color: "m" },
      { text: "  Web: janroca.taller          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 322       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 323,
    title: "ARTESA 323",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  NUR ALCARAZ / TEXTIL         ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: tint natural, patrons   ", color: "c" },
      { text: "  i peces de producció curta.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: nur@espai42.art    ", color: "m" },
      { text: "  IG: @nuralcaraz.textil       ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar artesania: pàg 320    ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 323       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 330,
    title: "MAKERS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  MAKERS / INDEX               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart inspirat en         ", color: "m" },
      { text: "  Leonardo da Vinci.           ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  331  Ada Prat (electrònica)  ", color: "c" },
      { text: "  332  Pol Serra (impressió 3D)", color: "c" },
      { text: "  333  Iris Valls (robots)     ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 330       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 331,
    title: "MAKER 331",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ADA PRAT / ELECTRONICA       ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: sintetitzadors DIY i    ", color: "c" },
      { text: "  sensors per instal·lacions.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: ada@espai42.art    ", color: "m" },
      { text: "  IG: @adaprat.makes           ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 331       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 332,
    title: "MAKER 332",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  POL SERRA / IMPRESSIO 3D     ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: prototips, recanvis      ", color: "c" },
      { text: "  i eines per tallers locals.  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: pol@espai42.art    ", color: "m" },
      { text: "  Web: polserra.maker          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 332       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 333,
    title: "MAKER 333",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  IRIS VALLS / ROBOTICA        ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: robots cinètics i       ", color: "c" },
      { text: "  automatismes escènics.       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: iris@espai42.art   ", color: "m" },
      { text: "  IG: @iris.valls.lab          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar makers: pàg 330       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 333       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 340,
    title: "OFICIS",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  OFICIS / INDEX               ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Pixelart: persona bufant     ", color: "m" },
      { text: "  vidre al forn del taller.    ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  341  Joana Clot (vidre)      ", color: "c" },
      { text: "  342  Arnau Gelabert (ferro)  ", color: "c" },
      { text: "  343  Teia Roig (enquadern.)  ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Tornar a residents: pàg 300  ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 340       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 341,
    title: "OFICI 341",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  JOANA CLOT / VIDRE           ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: llumins, gerros i       ", color: "c" },
      { text: "  escultura de vidre bufat.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: joana@espai42.art  ", color: "m" },
      { text: "  IG: @joanaclot.glass         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 341       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 342,
    title: "OFICI 342",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  ARNAU GELABERT / FERRO       ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: forja artística i       ", color: "c" },
      { text: "  estructures per interior.    ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: arnau@espai42.art  ", color: "m" },
      { text: "  Tel: +34 600 340 342         ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 342       ESPai42        ", color: "g" },
    ],
  },
  {
    num: 343,
    title: "OFICI 343",
    lines: [
      { text: "                              ", color: "w" },
      { text: "  TEIA ROIG / ENQUADERNACIO    ", color: "y" },
      { text: "                              ", color: "w" },
      { text: "  Bio: llibreta artesanal,     ", color: "c" },
      { text: "  pell i paper reciclat.       ", color: "c" },
      { text: "                              ", color: "w" },
      { text: "  Contacte: teia@espai42.art   ", color: "m" },
      { text: "  Web: teiaroig.ofici          ", color: "m" },
      { text: "                              ", color: "w" },
      { text: "  Tornar oficis: pàg 340       ", color: "w" },
      { text: "                              ", color: "w" },
      { text: "  Pàg 343       ESPai42        ", color: "g" },
    ],
  },
];

const pageMap = new Map(TELETEXT_PAGES.map((p) => [p.num, p]));

export function getTeletextPage(num: number): TeletextPageDef | undefined {
  return pageMap.get(num);
}

export const KNOWN_PAGE_NUMS = TELETEXT_PAGES.map((p) => p.num).sort((a, b) => a - b);
